CREATE USER jflanegan
IDENTIFIED BY password;

//2. login denied without create session

GRANT CREATE SESSION, CREATE ANY TABLE, ALTER ANY TABLE
TO jflanegan;

CREATE ROLE CUSTOMERREP;
GRANT INSERT, DELETE
ON STUDENT.ORDERS
TO CUSTOMERREP;
GRANT INSERT, DELETE
ON STUDENT.ORDERITEMS
TO CUSTOMERREP;

GRANT CUSTOMERREP
TO jflanegan;

//6. login as jflanegan and determine privilidges...derp

REVOKE DELETE
ON STUDENT.ORDERS
FROM CUSTOMERREP;
REVOKE DELETE
ON STUDENT.ORDERITEMS
FROM CUSTOMERREP;

REVOKE CUSTOMERREP
FROM jflanegan;

DROP ROLE CUSTOMERREP;

DROP USER jflanegan;